apiVersion : apps/v1
kind: Deployment
metadata:
  name: authorisationapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorisationapi
  template:
    metadata:
      labels:
        app: authorisationapi 
    spec:
      containers:
        - name: authorisationapi 
          image: acrvod.azurecr.io/authorisationapi
          ports:
          - containerPort: 80